config/routes.rb
Rails.application.routes.draw do
  get 'cartitems/create'

  root 'tops#main'
  get 'tops/main'

  resources :products, only: [:index, :new, :create, :destroy]
  resources :cartitems, only: [:create, :destroy]
  resources :carts, only: [:show]
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cartitems, dependent: :destroy
end

app/models/cartitem.rb
class Cartitem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name,  :price
  belongs_to :cart
  has_many :cartitems, dependent: :destroy
  has_many :cartitems_cart, source: :cart, through: :cartitems
  
  def add_item(cart, quantity)
    cartitems.create(cart_id: cart.id, quantity: quantity)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart
  
  private
	def current_cart
		if session[:cart_id]
			cart = Cart.find(session[:cart_id])
		else
		  cart = Cart.create
		  session[:cart_id] = cart.id
		end
		cart
	end
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController

  def create
    product = Product.find(params[:product_id])
    product.add_item(current_cart, params[:quantity])
    flash[:notice] = "カートに追加しました"
    redirect_to cart_path(current_cart.id)
  end
  
  def destroy
    Cartitem.find(params[:id]).destroy
    redirect_to cart_path(current_cart.id)
    flash[:notice] = "カートから削除しました"
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @items = Cartitem.where(cart_id: current_cart)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def new
    @products = Product.all
    @product = Product.new
  end
  
  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    if @product.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to new_product_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
	def main
		@products = Product.all
		render 'products/index'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitem_helper.rb
module CartitemHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/cartitems/create.html.erb
<h1>Cartitems#create</h1>
<p>Find me in app/views/cartitems/create.html.erb</p>

app/views/carts/show.html.erb
<%= link_to '買い物を続ける', '/' %>
</br>
<hr style="border:1px dashed #87CEEB;">
</br>

<% unless @items.empty? %>
	
	<% goukei = 0 %>

	<table>
  <tr>
    <th colspan="4">カート一覧</th>
  </tr>
  <tr>
    <th>商品</th><th>価格</th><th>数量</th><th>　　</th>
  </tr>
  
  <% @items.each do |c| %>
		<tr>
			<td><%= c.product.name %></td>
			<td>￥<%= c.product.price %></td>
			<td><%= c.quantity %></td>
			<td>
				<%= link_to '削除', cartitem_path(c), method: :delete, data: { confirm: '削除していいですか？' } %>
			</td>
		</tr>
		
		<% goukei = goukei + c.product.price.to_i * c.quantity.to_i %>
	<% end %>
	
	<tr>
    <th colspan="4">合計金額：￥<%= goukei  %></th>
  </tr>
</table>
	
<% else %>
	カートには何も入っていません。
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShopApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<p>
	<%= link_to '商品を登録する', new_product_path %>
	&emsp;
	<%= link_to 'カートを見る', cart_path(current_cart.id) %>
</p>
<hr style="border:1px dashed #87CEEB;">
</br>

<table>
  <tr>
    <th colspan="4">商品一覧</th>
  </tr>
  <tr>
    <th>商品</th><th>価格</th><th>数量</th><th>　　</th>
  </tr>
  
  <% @products.each do |p| %>
		<tr>
			<td><%= p.name %></td>
			<td>￥<%= p.price %></td>
			<%= form_tag cartitems_path(product_id: p.id) do %></td>
				<td><%= text_field_tag :quantity, 1, size: 2 %></td>
				<td><%= submit_tag 'カートに入れる' %>
				<% end %>
			</td>
		</tr>
	<% end %>
</table>

app/views/products/new.html.erb
<%= link_to '買い物をする', '/' %>
</br>
<hr style="border:1px dashed #87CEEB;">
</br>

<%= form_for @product do |s| %>
	<%= s.label :name, '商品名：' %></td>
	<%= s.text_field :name, required: 'required' %>
	&ensp;
	<%= s.label :price, '価格：' %>
	<%= s.text_field :price, required: 'required' %>
	&ensp;
	<%= s.submit '商品を登録' %>
<% end %>

</br></br>

<table>
  <tr>
    <th colspan="3">商品一覧</th>
  </tr>
  <tr>
    <th>商品</th><th>価格</th><th>　　</th>
  </tr>
  
  <% @products.each do |p| %>
		<tr>
			<td><%= p.name %></td>
			<td>￥<%= p.price %></td>
			<td>
				<%= link_to '削除', product_path(p), method: :delete, data: { confirm: '削除していいですか？' } %>
			</td>
		</tr>
	<% end %>
</table>

app/views/tops/main.html.erb
<h1>Tops#main</h1>
<p>Find me in app/views/tops/main.html.erb</p>